### ISSUE TITLE
v0.8.0 - Crash on new player join

### ISSUE THREAD

**Issue by CrowsOfWar** [CrowsOfWar/PhysicalTraits#9]
**This only applies to Physical Traits v0.8.0, a development version not easily available.**

When a new player joins, a crash occurs due to GoreCorePlayerUUIDs#getUUIDPerformance returning null.

**Comment by CrowsOfWar** [comment]
I'm unable to reproduce this problem... closed for now

**Comment by DarianLStephens** [comment]
I've been able to reliably reproduce this error within a MultiMC instance, in case it helps.
The log is as follows
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at crowsofwar.physicaltraits.common.events.PhysicalTraitsPlayerTicker.tickPlayer(PhysicalTraitsPlayerTicker.java:64)
	at crowsofwar.physicaltraits.common.events.PhysicalTraitsPlayerTicker.onWorldTick(PhysicalTraitsPlayerTicker.java:50)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_77_PhysicalTraitsPlayerTicker_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:268)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 209546736 bytes (199 MB) / 666894336 bytes (636 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_C1 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1462-universal.jar) 
	UCHIJAAAA	DimensionInventorys{0.1} [Dimension Inventorys] (DimensionInventorys-0.1.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	GoreCore{1.7.10-0.8.2} [GoreCore] (gorecore-1.7.10-0.8.2.jar) 
	UCHIJAAAA	hungryanimals{1.7.10-10.13.2.1291-1.0.4.2} [Hungry Animals] (hungryanimals-1.7.10-2.0.alpha02.jar) 
	UCHIJAAAA	hungryZombies{1.2.0} [Hungry Zombies] (hungryzombies-1.7.10-1.2.0.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.12.9} [MalisisCore] (malisiscore-1.7.10-0.12.9.jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.10} [Malisis' Doors] (malisisdoors-1.7.10-1.10.jar) 
	UCHIJAAAA	RadixCore{2.0.3} [RadixCore] (RadixCore-1.7.10-2.0.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive] (MCA-1.7.10-5.0.7.2-universal.jar) 
	UCHIJAAAA	samsmountedpearl{1.7.10-1.0.0} [Mounted Pearl] (MountedPearl-1.7.10-1.0.0.jar) 
	UCHIJAAAA	natureoverhaul{0.10.0} [Nature Overhaul] (NatureOverhaul-0.10.0(1.7.10).jar) 
	UCHIJAAAA	NEIAddons{1.12.11.36} [NEI Addons] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo] (neiaddons-1.12.11.36-mc1.7.10.jar) 
	UCHIJAAAA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJAAAA	NoMoreNerdPoles{1.0.0} [NoMoreNerdPoles] (NoMoreNerdPoles-1.7.10-1.0.0.jar) 
	UCHIJAAAA	PhysicalTraits{1.7.10-0.8.0} [Physical Traits] (physicaltraits-1.7.10-0.8.0.jar) 
	UCHIJAAAA	simply_sit{1.7.10-1.1.0} [Simply Sit] (SimplySit-1.7.10-1.1.0.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 8; [EntityPlayerMP['DarianStephens'/480, l='Gahasstoasdl', x=548.44, y=68.00, z=1280.00], EntityPlayerMP['Sienna'/41342, l='Gahasstoasdl', x=551.50, y=58.00, z=1270.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
